---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: chef12.4
    driver_config:
      image: centos
      platform: rhel
    provisioner:
      require_chef_omnibus: 12.4
  - name: chef12.3
    driver_config:
      image: centos
      platform: rhel
    provisioner:
      require_chef_omnibus: 12.3


suites:
  - name: default
    run_list:
      - recipe[lwrp_example::default]
    attributes:
